### Testing Funds 

##### Authors: Leonardo & Esteban

In [1]:
#### Importing packages
import pandas as pd
import numpy as np
import matplotlib as mlt
import os
import matplotlib.pyplot as plt

In [3]:
#### LUX FUNDS 
lux = pd.read_csv("LUX_funds.csv",sep = ",")

#### Lux Data 
- Static data from the available funds gathered. For quantitative reasearch might not be useful as there is no variaion over time.

In [5]:
lux.head()

,ISIN,TypeName,SecurityMarketName,QuantityType,TradingCurrency,MIC,CoursPrice,ClosingPriceDateTime,ClosingPriceType,NominalCumulJour,...,Sharpe_Ratio,1d_ret_perc,YTD_return,50d_avg,52w_High,52w_Low,Bond_pos,Convertible_pos,Cash,Summary
0,LU0028051117,Fund,"Universe, The CMI Global Network Fund CMI UK E...",UNT,GBP,EMTF,15.464,2022-12-02 16:33:00,Indicative price,0.0,...,11.294310,-0.914870,0.1078,1441.91400,1576.900,14.773,0.0000,0.0000,0.0092,NaN
1,LU0028051380,Fund,"Universe, The CMI Global Network Fund UK Equit...",UNT,GBP,EMTF,21.730,2022-12-02 16:33:00,Indicative price,0.0,...,6.971090,-0.633001,0.1064,2053.93000,2198.700,20.471,0.0004,0.0001,0.0065,NaN
2,LU0028049483,Fund,"Universe, The CMI Global Network Fund CMI US D...",UNT,USD,EMTF,10.398,2022-12-02 15:33:00,Indicative price,0.0,...,23.985724,-0.086553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LU0048620586,Fund,Fidelity Funds Flexible Bond Fund A GBP Distri...,UNT,GBP,EMTF,0.293,2022-12-02 07:42:00,Indicative price,0.0,...,1.960202,0.340137,-0.0128,28.33200,33.100,0.326,0.7299,0.0346,-0.0535,The fund aims to achieve income and capital gr...
4,LU0051200391,Fund,"Universe, The CMI Global Network Fund CMI Euro...",UNT,EUR,EMTF,23.535,2022-12-02 16:32:00,Indicative price,0.0,...,18.943863,-0.110517,-0.0027,23.43366,23.841,23.363,0.5122,0.0000,0.4180,NaN

In [6]:
#### Prices per Fund
fund = pd.read_csv("PRICES PER FUND/LU0011846440.csv",sep=",")
fund.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2022-03-14,162.440002,162.440002,162.440002,162.440002,0,0,0
1,2022-03-15,161.309998,161.309998,161.309998,161.309998,0,0,0
2,2022-03-16,169.190002,169.190002,169.190002,169.190002,0,0,0
3,2022-03-17,169.440002,169.440002,169.440002,169.440002,0,0,0
4,2022-03-18,172.279999,172.279999,172.279999,172.279999,0,0,0

In [8]:
fund.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,148.000000,148.000000,148.000000,148.000000,148.0,148.0,148.0
mean,151.646960,151.646960,151.646960,151.646960,0.0,0.0,0.0
std,10.295609,10.295609,10.295609,10.295609,0.0,0.0,0.0
min,134.070007,134.070007,134.070007,134.070007,0.0,0.0,0.0
25%,143.852497,143.852497,143.852497,143.852497,0.0,0.0,0.0
50%,151.934998,151.934998,151.934998,151.934998,0.0,0.0,0.0
75%,156.359997,156.359997,156.359997,156.359997,0.0,0.0,0.0
max,176.710007,176.710007,176.710007,176.710007,0.0,0.0,0.0